package com.example.voice_assistant.entity.enums;

/** Where a recipe originally came from. */
public enum RecipeSource {
    ANCESTOR,      // uploaded by voice from a family member / grandma's recipe
    AI_GENERATED   // generated by the AI because it wasn't found in the DB
}
